# Generated by Django 4.0.1 on 2022-01-26 17:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_doctoravailability_available_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='available_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=20, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='available_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='available_start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='available_status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=50),
        ),
    ]
