# Generated by Django 4.0.1 on 2022-01-27 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_doctorprofile_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hours', models.JSONField(default={'days': '[]', 'end_time': '', 'start_time': ''})),
            ],
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='available_end_time',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='available_start_time',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='doctor',
            field=models.OneToOneField(limit_choices_to={'user_type': 'doctor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
