# Generated by Django 4.0.1 on 2022-01-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_testavailability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testavailability',
            name='working_hours',
            field=models.JSONField(default=dict),
        ),
    ]
