# Generated by Django 4.0.1 on 2022-01-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_testavailability_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='working_hours',
            field=models.JSONField(default=dict),
        ),
    ]
