# Generated by Django 4.0.1 on 2022-01-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_doctoravailability_working_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='working_hours',
            new_name='working_shifts',
        ),
    ]
