# Generated by Django 4.0.1 on 2022-01-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_workingshift_doctor_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='doctor',
            new_name='doctor_profile',
        ),
        migrations.RenameField(
            model_name='workingshift',
            old_name='doctor_availability',
            new_name='doctor_profile',
        ),
        migrations.AlterUniqueTogether(
            name='workingshift',
            unique_together={('doctor_profile', 'working_day')},
        ),
    ]
