# Generated by Django 4.0.1 on 2022-01-27 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_doctor_doctoravailability_doctor_profile_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workingshift',
            unique_together=set(),
        ),
    ]
