# Generated by Django 4.0.1 on 2022-02-10 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_patientprofile_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='patient',
            field=models.OneToOneField(limit_choices_to={'user_type': 'patient'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
