# Generated by Django 4.0.1 on 2022-02-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_patientprofile_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='nmc',
            field=models.IntegerField(default=0),
        ),
    ]
