# Generated by Django 4.0.1 on 2022-02-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_patientprofile_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='nmc',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
