# Generated by Django 4.0.1 on 2022-02-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_doctorprofile_nmc'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='nmc_verified',
            field=models.BooleanField(default=False),
        ),
    ]
