# Generated by Django 4.0.1 on 2022-02-25 09:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_doctorprofile_nmc_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
