# Generated by Django 4.0.1 on 2022-03-06 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.IntegerField(choices=[(0, '09:00 - 09:30'), (1, '09:30 - 10:00'), (2, '10:00 - 10:30'), (3, '10:30 - 11:00'), (4, '11:00 - 11:30'), (5, '11:30 - 12:00'), (6, '12:00 - 12:30'), (7, '12:30 - 13:00'), (8, '13:00 - 13:30'), (9, '13:30 - 14:00'), (10, '14:00 - 14:30'), (11, '14:30 - 15:00'), (12, '15:00 - 15:30'), (13, '15:30 - 16:00'), (14, '16:00 - 16:30'), (15, '16:30 - 17:00'), (16, '17:00 - 17:30')], default=100)),
                ('reason', models.CharField(max_length=254)),
                ('description', models.TextField(null=True)),
                ('approval_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('deleted', 'Deleted'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
