# Generated by Django 4.0.1 on 2022-04-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='history_files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
