# Generated by Django 4.0.1 on 2022-02-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='pending', max_length=10),
        ),
    ]
