# Generated by Django 4.0.1 on 2022-02-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('deleted', 'Deleted'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
